### ISSUE TITLE
OS X support?

### ISSUE THREAD

**Issue by xgalaxy** [SwiftValidatorCommunity/SwiftValidator#103]
Would love it if this supported NSTextField and NSLabel. Not sure what abstraction would be necessary to achieve this. Perhaps have OS specific versions of registerField gated behind a compile flag which take either NSTextField and UITextField. Hide the NSTextField or UITextField behind a protocol that lets you get and set the text. Then the rest of the code base just talks to the protocol instead of the textfield directly.

**Comment by davepatterson** [comment]
Perhaps this is something that we will consider in the future but it isn't currently on the radar. I honestly have never even done dev work in OS X.

**Comment by jpotts18** [comment]
@xgalaxy Are you interested in contributing?

**Comment by Arti3DPlayer** [comment]
+1

**Comment by jpotts18** [comment]
I'm not going to lie this project took off and I'm pretty overwhelmed by it. I no longer actively code in Swift and I need help from more contributors in order to keep this project relevant. I'd like to find someone to transition as lead maintainer or help this codebase find a happy home with a company.

The codebase for this project is relatively small and focused project for who is looking to contribute. It does one thing, and does it pretty well. It has pretty high test coverage and good adoption. I think my ideal maintainer / contributor would work for a company that actively uses SwiftValidator in their production application.

If you're interested in helping out please comment on #204
