### ISSUE TITLE
Validator returns all error messages associated with textfield

### ISSUE THREAD

**Issue by w007up** [SwiftValidatorCommunity/SwiftValidator#108]
Hi Is there a way where the validator returns all the error messages associated with the textfield rather than just returning the error message associated to the first rule that it fails on?

For example a text field has a RequiredRule(), MinLengthRule(6), RegexRule(1digit), RegexRule(1letter).

When the user focuses on this textfield a message is displayed stating:

"This is a required field. Minimum Length 6. One number. One Letter."

As each rule is satisfied the message associated with that rule disappears.

Thanks

**Comment by davepatterson** [comment]
There actually is not as of right now. `ValidationRule`'s validateField() method only returns the first one that fails. Here's the code snippet: 

`return rules.filter{ !$0.validate(self.textField.text ?? "") }
                    .map{ rule -> ValidationError in return ValidationError(textField: self.textField, errorLabel:self.errorLabel, error: rule.errorMessage()) }.first`

**Comment by racer1988** [comment]
@w007up  You can do what you just said by using a single regex rule satisfying all the rules

    ^(?=.*[0-9])(?=.*[a-zA-Z])(.{6,})$

you can test it here
https://regex101.com/r/iI5uR2/1

I would suggest to use this for complex rules with one single message, and close this issue instead?

**Comment by davepatterson** [comment]
@racer1988 I understand your suggestion of using a regular expression that includes all the rules but I think what @w007up was asking is how will he notify which rule has failed. The regular expression will just display the same error message each time. For example, say a user types one letter (thus fulfilling two of the requirements of the regular expression) but doesn't satisfy the other constraints of the regular expression. The resulting error message would still display "This is a required field. Minimum Length 6. One number. One Letter." when in fact it should show "Minimum Length 6. One number."

**Comment by racer1988** [comment]
Ah ok, he wants multiple strings to be concatenated and removed based on the active validation.

That is a nice improvement but requires quite some new work on the validation part. 
maybe it could be a separate validation method

**Comment by davepatterson** [comment]
For sure. It will definitely require a separate validation method as the current one only returns the first rule that fails.

**Comment by jpotts18** [comment]
Declaring Backlog Bankruptcy!

I'm not going to lie this project took off and I'm pretty overwhelmed by it. I no longer actively code in Swift and I need help from more contributors in order to keep this project relevant. I'd like to find someone to transition as lead maintainer or help this codebase find a happy home with a company.

The codebase for this project is relatively small and focused project for who is looking to contribute. It does one thing, and does it pretty well. It has pretty high test coverage and good adoption. I think my ideal maintainer / contributor would work for a company that actively uses SwiftValidator in their production application.

If you're interested in helping out please comment on #204
