### ISSUE TITLE
problem with regex for letters and numbers only

### ISSUE THREAD

**Issue by nalogowiec** [SwiftValidatorCommunity/SwiftValidator#170]
I'm adding regex for escaping anything that is not a number or letter.

This is my rule:

`validator.registerField(usernameTextField, rules: [RequiredRule(), FullNameRule(), RegexRule(regex: "\\w"), MaxLengthRule(), MinLengthRule()])`

It does not work and always fails. Why?

**Comment by jpotts18** [comment]
I'm not going to lie this project took off and I'm pretty overwhelmed by it. I no longer actively code in Swift and I need help from more contributors in order to keep this project relevant. I'd like to find someone to transition as lead maintainer or help this codebase find a happy home with a company.

The codebase for this project is relatively small and focused project for who is looking to contribute. It does one thing, and does it pretty well. It has pretty high test coverage and good adoption. I think my ideal maintainer / contributor would work for a company that actively uses SwiftValidator in their production application.

If you're interested in helping out please comment on #204
