### ISSUE TITLE
Use version numbers instead of master branch

### ISSUE THREAD

**Issue by PranKe01** [SwiftValidatorCommunity/SwiftValidator#180]
Hi,
to make our projects versionable, it would be nice if you could create a branch with the correct version number, instead of using the master branch (at leats for swift 3). If you update the master branch it is not possible to keep the "old" running version of SwiftValidator...

Thanks =)

**Comment by rajatjain4061** [comment]
@PranKe01 Thank you for your suggestion. Library is now maintained according to seperate branches

**Comment by jpotts18** [comment]
I'm not going to lie this project took off and I'm pretty overwhelmed by it. I no longer actively code in Swift and I need help from more contributors in order to keep this project relevant. I'd like to find someone to transition as lead maintainer or help this codebase find a happy home with a company.

The codebase for this project is relatively small and focused project for who is looking to contribute. It does one thing, and does it pretty well. It has pretty high test coverage and good adoption. I think my ideal maintainer / contributor would work for a company that actively uses SwiftValidator in their production application.

If you're interested in helping out please comment on #204
