### ISSUE TITLE
Cannot profile the project because SwiftValidator error: 'ValidatableField' is not a subtype of 'UITextField'

### ISSUE THREAD

**Issue by peihsendoyle** [SwiftValidatorCommunity/SwiftValidator#189]
Like I said on the title, we I profile (to check leak memory) I got this. (attachments)
<img width="736" alt="screen shot 2017-07-01 at 7 37 33 am" src="https://user-images.githubusercontent.com/7514128/27757779-600a79cc-5e30-11e7-8abb-4bbd70a8d670.png">
<img width="735" alt="screen shot 2017-07-01 at 7 37 38 am" src="https://user-images.githubusercontent.com/7514128/27757780-6020d4ba-5e30-11e7-988d-0dfa42cb0f64.png">

**Comment by dungnc** [comment]
i have a same problem :(((

**Comment by NikhilDevgire** [comment]
I have the same issue. Not able to create the build.

**Comment by hadeerkamel** [comment]
add "as! UITextField"
    1- return (confirmField as! UITextField).validationText == value
    2- return !$0.validate((field as! UITextField).validationText)

**Comment by hadeerkamel** [comment]
add "as! UITextField"
1-return (confirmField as! UITextField).validationText == value
2-return !$0.validate((field as! UITextField).validationText)

**Comment by jpotts18** [comment]
I'm not going to lie this project took off and I'm pretty overwhelmed by it. I no longer actively code in Swift and I need help from more contributors in order to keep this project relevant. I'd like to find someone to transition as lead maintainer or help this codebase find a happy home with a company.

The codebase for this project is relatively small and focused project for who is looking to contribute. It does one thing, and does it pretty well. It has pretty high test coverage and good adoption. I think my ideal maintainer / contributor would work for a company that actively uses SwiftValidator in their production application.

If you're interested in helping out please comment on #204
