### ISSUE TITLE
Docs are 404

### ISSUE THREAD

**Issue by tkirby** [SwiftValidatorCommunity/SwiftValidator#191]
https://jpotts18.github.io/SwiftValidator/

**Comment by omidshz100** [comment]
please help me , how can access to docs ??

**Comment by jpotts18** [comment]
I'm not going to lie this project took off and I'm pretty overwhelmed by it. I no longer actively code in Swift and I need help from more contributors in order to keep this project relevant. I'd like to find someone to transition as lead maintainer or help this codebase find a happy home with a company.

The codebase for this project is relatively small and focused project for who is looking to contribute. It does one thing, and does it pretty well. It has pretty high test coverage and good adoption. I think my ideal maintainer / contributor would work for a company that actively uses SwiftValidator in their production application.

If you're interested in helping out please comment on #204

**Comment by jpotts18** [comment]
This has been updated!
http://swiftvalidatorcommunity.github.io/SwiftValidator/
