### ISSUE TITLE
Add phone number rule for UK numbers

### ISSUE THREAD

**Issue by StephenClarkApps** [SwiftValidatorCommunity/SwiftValidator#194]
Please can you add a UKPhoneNumberRule which is identical to PhoneNumberRule but with character limit set to 11 and not ten.   A typical UK cell phone number might be something like:  07908957211

**Comment by jpotts18** [comment]
I'm not going to lie this project took off and I'm pretty overwhelmed by it. I no longer actively code in Swift and I need help from more contributors in order to keep this project relevant. I'd like to find someone to transition as lead maintainer or help this codebase find a happy home with a company.

The codebase for this project is relatively small and focused project for who is looking to contribute. It does one thing, and does it pretty well. It has pretty high test coverage and good adoption. I think my ideal maintainer / contributor would work for a company that actively uses SwiftValidator in their production application.

If you're interested in helping out please comment on #204
