### ISSUE TITLE
Problem with regex rule

### ISSUE THREAD

**Issue by aluco100** [SwiftValidatorCommunity/SwiftValidator#196]
Hi,

I'm trying to set a rule for phone validation. I need a phone begins with '+56' so I register my field with this configuration:

`validator.registerField(self.formTextField, rules: [RequiredRule(message: "The phone is required"),RegexRule(regex: "^((\\+)56)", message: "The phone must begins with +56")])`

What could be happen?

If anybody help me I'll really appreciated.

Regards

**Comment by jpotts18** [comment]
I'm not going to lie this project took off and I'm pretty overwhelmed by it. I no longer actively code in Swift and I need help from more contributors in order to keep this project relevant. I'd like to find someone to transition as lead maintainer or help this codebase find a happy home with a company.

The codebase for this project is relatively small and focused project for who is looking to contribute. It does one thing, and does it pretty well. It has pretty high test coverage and good adoption. I think my ideal maintainer / contributor would work for a company that actively uses SwiftValidator in their production application.

If you're interested in helping out please comment on #204
