### ISSUE TITLE
Make validationSuccess() optional

### ISSUE THREAD

**Issue by richardtop** [SwiftValidatorCommunity/SwiftValidator#44]
Often only the errors are required, so you do not need validationSuccess()  at all. But still, I am required to implement an empty function.

**Comment by driver733** [comment]
+1

**Comment by jpotts18** [comment]
How do you detect if all fields are valid?

**Comment by richardoti** [comment]
@jpotts18 if there is no errors -> all fields are valid.

**Comment by jpotts18** [comment]
Declaring Backlog Bankruptcy!!

I'm not going to lie this project took off and I'm pretty overwhelmed by it. I no longer actively code in Swift and I need help from more contributors in order to keep this project relevant. I'd like to find someone to transition as lead maintainer or help this codebase find a happy home with a company.

The codebase for this project is relatively small and focused project for who is looking to contribute. It does one thing, and does it pretty well. It has pretty high test coverage and good adoption. I think my ideal maintainer / contributor would work for a company that actively uses SwiftValidator in their production application.

If you're interested in helping out please comment on #204
