### ISSUE TITLE
Why use delegate or callbacks for validation?

### ISSUE THREAD

**Issue by i-schuetz** [SwiftValidatorCommunity/SwiftValidator#47]
I was wondering about the reason to pass a delegate or callback for the validation. Maybe the reason is to be able to return either success or error.

Instead you could just return an optional error dictionary, so validation result can be easily handled using if let:

``` swift
if let errors = validator.validate() {
    // do sth with errors
} else {
    // success
}
```

This is much more convenient than having to implement a delegate. A callback is similar, but this is better as I don't see any legitimate reason to use callbacks.

Then it's also possible to remove "errors" instance variable from Validator, don't see any advantage of this except maybe storing last possible error but the implementation has to be adjusted a bit for that.

For the result I also thought about using an Either enum, in Swift 2, but an optional is more convenient as it's possible to use if let directly on the result and the success state doesn't have any payload. Either may be more accurate signalising the possible results but it's less convenient, and the meaning of the optional should be obvious IMO.

Would it make sense to do this change? Or is there anything I'm missing?

If the change is welcome I can submit a PR (child of Swift 2 commit).

You can see the changes here https://github.com/i-schuetz/SwiftValidator/commit/5e9e922d7bc3e4ecb1bfca1e5468b82de0627aa8 (all tests passing)

**Comment by richardoti** [comment]
@i-schuetz nice idea!

**Comment by ishaq** [comment]
+1

**Comment by jpotts18** [comment]
Declaring Backlog Bankruptcy!

I'm not going to lie this project took off and I'm pretty overwhelmed by it. I no longer actively code in Swift and I need help from more contributors in order to keep this project relevant. I'd like to find someone to transition as lead maintainer or help this codebase find a happy home with a company.

The codebase for this project is relatively small and focused project for who is looking to contribute. It does one thing, and does it pretty well. It has pretty high test coverage and good adoption. I think my ideal maintainer / contributor would work for a company that actively uses SwiftValidator in their production application.

If you're interested in helping out please comment on #204
